/**
 * Datos del catálogo de iconos de categoría — SIN React ni componentes.
 *
 * Vive separado de `categoryIcons.ts` a propósito: los componentes de Tabler
 * arrastran react-native, y estos datos los usan el sugeridor y sus tests, que
 * corren en Node (`npx tsx utils/suggestIcon.test.ts`).
 */

/** Icono de la categoría "Otro" y red de seguridad de todo lo que no resuelve. */
export const FALLBACK_ICON = 'pin';

export const CATEGORY_ICON_GROUPS: { id: string; icons: string[] }[] = [
  {
    id: 'food',
    icons: ['tools-kitchen', 'pizza', 'burger', 'meat', 'fish', 'salad', 'soup', 'bread',
      'cheese', 'ice-cream', 'cake', 'candy', 'cookie', 'coffee', 'cup', 'beer',
      'wine', 'bottle', 'milk', 'egg', 'carrot', 'apple', 'lemon', 'chef-hat',
      'grill', 'bowl', 'shopping-cart', 'basket'],
  },
  {
    id: 'transport',
    icons: ['car', 'car-suv', 'bus', 'train', 'plane', 'bike', 'motorbike', 'scooter',
      'gas-station', 'parking', 'road', 'ship', 'helicopter', 'walk', 'steering-wheel',
      'truck', 'traffic-lights', 'map', 'map-pin'],
  },
  {
    id: 'health',
    icons: ['pill', 'stethoscope', 'heart-rate', 'vaccine', 'dental', 'eyeglass',
      'first-aid', 'nurse', 'wheelchair', 'massage', 'yoga', 'barbell', 'run',
      'swimming', 'heartbeat', 'medical-cross', 'bandage', 'mood-smile'],
  },
  {
    id: 'fun',
    icons: ['movie', 'tv', 'music', 'headphones', 'gamepad', 'ticket', 'microphone',
      'book', 'palette', 'confetti', 'football', 'basketball', 'tennis', 'pool',
      'campfire', 'cards', 'chess', 'puzzle', 'guitar'],
  },
  {
    id: 'shopping',
    icons: ['shopping-bag', 'shirt', 'shoe', 'hanger', 'gift', 'diamond', 'backpack',
      'perfume', 'tag', 'sparkles', 'brush', 'haircut', 'scissors'],
  },
  {
    id: 'home',
    icons: ['home', 'sofa', 'bed', 'bulb', 'droplet', 'flame', 'wifi', 'plug', 'trash',
      'tools', 'hammer', 'key', 'building', 'cottage', 'wash-machine', 'air-conditioning',
      'bath', 'flower', 'plant', 'recycle'],
  },
  {
    id: 'money',
    icons: ['cash', 'banknote', 'credit-card', 'wallet', 'pig-money', 'report-money',
      'chart-line', 'coin', 'receipt', 'receipt-tax', 'bank', 'percentage', 'exchange',
      'certificate', 'shield', 'shield-check', 'businessplan'],
  },
  {
    id: 'work',
    icons: ['briefcase', 'laptop', 'school', 'book2', 'pencil', 'presentation', 'users',
      'skyscraper', 'clock', 'notebook', 'diploma', 'user-check', 'mail', 'phone'],
  },
  { id: 'pets', icons: ['paw', 'dog', 'cat', 'bone'] },
  {
    id: 'travel',
    icons: ['luggage', 'beach', 'mountain', 'world', 'camera', 'compass', 'tent',
      'sunset', 'monument'],
  },
  {
    id: 'tech',
    icons: ['mobile', 'desktop', 'printer', 'robot', 'cloud', 'battery', 'server',
      'antenna', 'smartwatch', 'router'],
  },
  {
    id: 'other',
    icons: ['heart', 'star', 'pin', 'baby', 'kid', 'user-heart', 'hand-love', 'church', 'cross'],
  },
];

/** Todas las claves del catálogo, en el orden en que se muestran. */
export const CATEGORY_ICON_NAMES: string[] = CATEGORY_ICON_GROUPS.flatMap((g) => g.icons);

const NAME_SET = new Set(CATEGORY_ICON_NAMES);

export function isCategoryIcon(value: string | undefined | null): boolean {
  return !!value && NAME_SET.has(value);
}

/**
 * Palabras → icono. Es la tabla que heredó `suggestEmoji` (misma cobertura de
 * español latinoamericano y marcas locales), traducida al catálogo. El orden
 * importa: lo específico va antes que lo genérico ("pizza" antes que "comida").
 */
export const KEYWORD_ICONS: [string[], string][] = [
  // Comida
  [['hamburguesa', 'burger', 'hamburguer'], 'burger'],
  [['pizza', 'pizzeria'], 'pizza'],
  [['sushi', 'japonesa', 'ramen', 'japones', 'wok'], 'fish'],
  [['pollo', 'chicken', 'asado', 'parrilla', 'bbq', 'brasa', 'carne', 'churrasco'], 'grill'],
  [['tacos', 'mexicana', 'burrito', 'quesadilla'], 'meat'],
  [['pasta', 'espagueti', 'italiana', 'lasagna'], 'soup'],
  [['ensalada', 'vegano', 'vegetariano', 'saludable', 'verdura'], 'salad'],
  [['sandwich', 'sub', 'wrap', 'perro caliente', 'hotdog'], 'bread'],
  [['arepa', 'bandeja', 'colombiana', 'sancocho', 'frijoles', 'sopa', 'caldo'], 'soup'],
  [['mariscos', 'camarones', 'pescado', 'langosta', 'ceviche'], 'fish'],
  [['helado', 'heladeria'], 'ice-cream'],
  [['postre', 'dulce', 'torta', 'pastel', 'cake', 'brownie'], 'cake'],
  [['galleta', 'cookie'], 'cookie'],
  [['chocolate', 'choco', 'caramelo', 'golosina'], 'candy'],
  [['fruta', 'fresas', 'mango', 'banano', 'manzana'], 'apple'],
  [['limon', 'citrico', 'jugos naturales'], 'lemon'],
  [['panaderia', 'pan', 'croissant', 'ponque'], 'bread'],
  [['queso', 'lacteos'], 'cheese'],
  [['leche', 'yogur'], 'milk'],
  [['huevo', 'huevos'], 'egg'],
  [['verduras', 'zanahoria', 'hortalizas'], 'carrot'],
  [['cafe', 'cafeteria', 'espresso', 'latte', 'tinto'], 'coffee'],
  [['desayuno', 'brunch', 'avena'], 'egg'],
  [['domicilio', 'rappi', 'ifood', 'delivery'], 'scooter'],
  [['cerveza', 'trago', 'licor', 'aguardiente', 'ron', 'whisky', 'cantina'], 'beer'],
  [['vino', 'copa', 'maridaje'], 'wine'],
  [['coctel', 'mojito', 'margarita', 'limonada'], 'cup'],
  [['agua', 'gaseosa', 'bebida', 'hidratacion', 'botella'], 'bottle'],
  [['chef', 'cocina', 'clase de cocina'], 'chef-hat'],
  [['supermercado', 'exito', 'carulla', 'jumbo', 'd1', 'ara', 'lidl', 'mercado'], 'shopping-cart'],
  // Transporte
  [['gasolina', 'combustible', 'nafta', 'tanqueo'], 'gas-station'],
  [['peaje', 'autopista', 'carretera'], 'road'],
  [['taxi', 'uber', 'didi', 'cabify', 'indriver'], 'car'],
  [['bus', 'buseta', 'transmilenio', 'metro', 'mio', 'sitp'], 'bus'],
  [['tren', 'ferrocarril'], 'train'],
  [['avion', 'vuelo', 'aeropuerto', 'aerolinea', 'tiquete'], 'plane'],
  [['bici', 'bicicleta', 'ciclovia', 'ciclismo'], 'bike'],
  [['moto', 'motocicleta'], 'motorbike'],
  [['patineta', 'scooter'], 'scooter'],
  [['parqueadero', 'parking', 'parqueo'], 'parking'],
  [['camion', 'mudanza', 'trasteo', 'flete'], 'truck'],
  [['barco', 'crucero', 'ferry'], 'ship'],
  [['multa', 'comparendo', 'sancion', 'semaforo'], 'traffic-lights'],
  [['caminar', 'caminata'], 'walk'],
  // Salud
  [['farmacia', 'drogueria', 'medicamento', 'pastilla', 'droga'], 'pill'],
  [['medico', 'doctor', 'consulta', 'clinica', 'hospital', 'urgencias'], 'stethoscope'],
  [['gym', 'gimnasio', 'crossfit', 'pesas', 'entrenamiento', 'fitness'], 'barbell'],
  [['yoga', 'meditacion', 'pilates', 'bienestar'], 'yoga'],
  [['optica', 'lentes', 'gafas'], 'eyeglass'],
  [['dental', 'odontologia', 'ortodoncista', 'muela'], 'dental'],
  [['psicologia', 'terapia', 'psiquiatria'], 'mood-smile'],
  [['vitamina', 'suplemento', 'proteina', 'creatina'], 'heartbeat'],
  [['vacuna', 'inyeccion'], 'vaccine'],
  [['enfermera', 'enfermeria'], 'nurse'],
  [['curacion', 'herida', 'botiquin'], 'first-aid'],
  [['discapacidad', 'silla de ruedas'], 'wheelchair'],
  [['spa', 'masaje', 'relajacion', 'facial'], 'massage'],
  [['natacion', 'piscina', 'aqua'], 'swimming'],
  [['correr', 'running', 'maraton', 'trail'], 'run'],
  // Ocio
  [['netflix', 'hbo', 'disney', 'prime', 'streaming'], 'tv'],
  [['spotify', 'apple music', 'deezer', 'musica'], 'music'],
  [['cine', 'pelicula', 'teatro', 'obra'], 'movie'],
  [['videojuego', 'playstation', 'xbox', 'nintendo', 'steam', 'consola', 'gaming'], 'gamepad'],
  [['concierto', 'evento', 'festival', 'show', 'boleta', 'karaoke'], 'ticket'],
  [['podcast', 'radio', 'microfono'], 'microphone'],
  [['libro', 'audible', 'kindle', 'lectura'], 'book'],
  [['guitarra', 'instrumento', 'banda'], 'guitar'],
  [['audifonos', 'airpods', 'earbuds'], 'headphones'],
  [['futbol', 'cancha', 'partido'], 'football'],
  [['basketball', 'baloncesto'], 'basketball'],
  [['tenis', 'padel', 'squash'], 'tennis'],
  [['billar', 'pool'], 'pool'],
  [['camping', 'fogata', 'senderismo'], 'campfire'],
  [['juegos de mesa', 'cartas', 'poker', 'casino'], 'cards'],
  [['ajedrez'], 'chess'],
  [['rompecabezas', 'escape room', 'bowling'], 'puzzle'],
  [['arte', 'pintura', 'manualidades'], 'palette'],
  // Compras y cuidado personal
  [['ropa', 'camisa', 'pantalon', 'vestido', 'falda', 'pijama'], 'shirt'],
  [['zapatos', 'tenis deportivos', 'botas', 'sandalias', 'zapatillas'], 'shoe'],
  [['bolso', 'cartera', 'maleta de mano', 'mochila'], 'backpack'],
  [['joyeria', 'aretes', 'collar', 'pulsera', 'anillo', 'joyas'], 'diamond'],
  [['amazon', 'mercadolibre', 'shein', 'aliexpress', 'online'], 'shopping-bag'],
  [['lavanderia', 'tintoreria', 'plancha'], 'hanger'],
  [['regalo', 'cumpleanos', 'navidad', 'obsequio', 'detalle'], 'gift'],
  [['perfume', 'colonia', 'fragancia'], 'perfume'],
  [['maquillaje', 'labial', 'cosmeticos', 'crema', 'locion', 'serum', 'belleza', 'estetica'], 'sparkles'],
  [['peluqueria', 'corte', 'barberia', 'tinte', 'manicure', 'pedicure', 'unas'], 'haircut'],
  [['descuento', 'oferta', 'promocion'], 'tag'],
  // Hogar
  [['arriendo', 'alquiler', 'renta', 'hipoteca'], 'home'],
  [['luz', 'energia', 'electrica', 'electricidad', 'epm'], 'bulb'],
  [['agua', 'acueducto', 'alcantarillado', 'ducha'], 'droplet'],
  [['gas', 'naturgas', 'gasnaturales'], 'flame'],
  [['internet', 'wifi', 'fibra', 'movistar', 'claro', 'tigo'], 'wifi'],
  [['mueble', 'sofa', 'sala'], 'sofa'],
  [['cama', 'colchon', 'dormitorio', 'armario'], 'bed'],
  [['decoracion', 'cuadro', 'lampara', 'alfombra', 'cortina'], 'plant'],
  [['limpieza', 'aseo', 'jabon', 'detergente', 'escoba', 'basura'], 'trash'],
  [['ferreteria', 'herramienta', 'reparacion', 'plomeria'], 'tools'],
  [['remodelacion', 'obra', 'construccion', 'pintura casa'], 'hammer'],
  [['lavadora', 'nevera', 'microondas', 'electrodomestico'], 'wash-machine'],
  [['aire acondicionado', 'ventilador', 'calefaccion'], 'air-conditioning'],
  [['bano', 'sanitario'], 'bath'],
  [['jardineria', 'plantas', 'semillas', 'flores'], 'flower'],
  [['reciclaje', 'sostenible'], 'recycle'],
  [['administracion', 'edificio', 'conjunto', 'portería'], 'building'],
  [['finca', 'campo', 'casa de campo'], 'cottage'],
  [['llaves', 'cerrajeria'], 'key'],
  // Dinero
  [['salario', 'sueldo', 'nomina', 'quincena', 'pago mensual'], 'cash'],
  [['efectivo', 'retiro', 'cajero'], 'banknote'],
  [['tarjeta', 'visa', 'mastercard'], 'credit-card'],
  [['inversion', 'dividendo', 'rendimiento', 'acciones', 'cripto', 'bolsa'], 'chart-line'],
  [['ahorro', 'alcancia', 'deposito'], 'pig-money'],
  [['prestamo', 'credito', 'deuda', 'cuota', 'banco'], 'bank'],
  [['transferencia', 'consignacion', 'remesa', 'cambio', 'divisa'], 'exchange'],
  [['bono', 'prima', 'comision', 'incentivo'], 'coin'],
  [['factura', 'recibo', 'cuenta de cobro'], 'receipt'],
  [['impuesto', 'dian', 'declaracion', 'iva', 'retefuente', 'predial'], 'receipt-tax'],
  [['seguro', 'poliza', 'axa', 'sura', 'mapfre'], 'shield'],
  [['abogado', 'notaria', 'juridico', 'legal'], 'certificate'],
  [['presupuesto', 'plan financiero', 'meta'], 'businessplan'],
  [['interes', 'porcentaje', 'tasa'], 'percentage'],
  [['reporte', 'balance', 'contabilidad'], 'report-money'],
  [['billetera', 'nequi', 'daviplata', 'wallet'], 'wallet'],
  // Trabajo y estudio
  [['freelance', 'honorarios', 'proyecto', 'cliente', 'trabajo', 'empleo', 'negocio', 'empresa'], 'briefcase'],
  [['curso', 'udemy', 'coursera', 'platzi', 'capacitacion', 'computador', 'laptop', 'macbook', 'pc'], 'laptop'],
  [['universidad', 'carrera', 'semestre', 'matricula', 'colegio', 'escuela', 'primaria', 'bachillerato'], 'school'],
  [['cuaderno', 'papeleria', 'lapiz', 'utiles'], 'pencil'],
  [['idioma', 'ingles', 'frances', 'clases'], 'book2'],
  [['reunion', 'conferencia', 'presentacion'], 'presentation'],
  [['equipo', 'socios', 'reunion equipo'], 'users'],
  [['oficina', 'coworking', 'home office', 'trabajo remoto'], 'skyscraper'],
  [['suscripcion', 'membresia', 'anualidad', 'mensualidad'], 'clock'],
  [['diploma', 'titulo', 'grado', 'certificacion'], 'diploma'],
  [['correo', 'envio', 'paqueteria', 'mensajeria'], 'mail'],
  [['telefonia', 'celular plan', 'minutos', 'recarga'], 'phone'],
  // Mascotas
  [['perro', 'dogfood', 'paseador'], 'dog'],
  [['gato', 'arena', 'felino'], 'cat'],
  [['veterinario', 'guarderia canina'], 'stethoscope'],
  [['comida mascota', 'concentrado', 'hueso'], 'bone'],
  // Viajes
  [['hotel', 'hostal', 'airbnb', 'alojamiento'], 'bed'],
  [['turismo', 'tour', 'excursion', 'paseo'], 'map'],
  [['vacaciones', 'viaje', 'viaje de negocios'], 'luggage'],
  [['visa', 'pasaporte', 'tramite viaje', 'extranjero'], 'world'],
  [['playa', 'mar', 'sol'], 'beach'],
  [['montana', 'senderismo', 'trekking'], 'mountain'],
  [['camping', 'carpa'], 'tent'],
  [['fotografia', 'sesion', 'estudio foto', 'camara', 'foto'], 'camera'],
  [['museo', 'monumento', 'cultura'], 'monument'],
  [['atardecer', 'mirador'], 'sunset'],
  [['brujula', 'aventura'], 'compass'],
  // Tecnología
  [['celular', 'telefono', 'iphone', 'android', 'samsung', 'tablet', 'ipad'], 'mobile'],
  [['escritorio', 'monitor', 'desktop'], 'desktop'],
  [['impresora', 'tinta', 'papel'], 'printer'],
  [['ia', 'inteligencia artificial', 'chatgpt', 'robot'], 'robot'],
  [['nube', 'icloud', 'dropbox', 'almacenamiento'], 'cloud'],
  [['bateria', 'cargador', 'power bank'], 'battery'],
  [['hosting', 'servidor', 'dominio', 'vps'], 'server'],
  [['antena', 'senal', 'router', 'modem'], 'router'],
  [['smartwatch', 'reloj inteligente', 'apple watch', 'reloj'], 'smartwatch'],
  // Personal y otros
  [['bebe', 'recien nacido', 'panal', 'formula'], 'baby'],
  [['juguete', 'lego', 'muneca', 'nino', 'hijo', 'jardin infantil'], 'kid'],
  [['familia', 'pareja', 'aniversario'], 'user-heart'],
  [['donacion', 'caridad', 'ong', 'voluntariado'], 'hand-love'],
  [['iglesia', 'diezmo', 'ofrenda', 'misa'], 'church'],
  [['emergencia', 'imprevisto', 'urgente'], 'medical-cross'],
  [['amor', 'san valentin', 'romantico'], 'heart'],
  [['favorito', 'destacado', 'premium'], 'star'],
  // Genéricos — al final a propósito: si el nombre trae algo específico
  // ("comida del perro"), gana lo específico.
  [['comida', 'restaurante', 'almuerzo', 'cena', 'rancho'], 'tools-kitchen'],
  [['transporte', 'carro', 'auto', 'vehiculo', 'conductor'], 'car'],
  [['salud', 'eps', 'medicina', 'seguro medico'], 'medical-cross'],
  [['fiesta', 'rumba', 'discoteca', 'clubbing', 'ocio', 'entretenimiento', 'diversion', 'hobby'], 'confetti'],
  [['tienda', 'boutique', 'moda', 'shopping', 'centro comercial', 'compras'], 'shopping-bag'],
  [['hogar', 'casa', 'vivienda', 'servicios'], 'home'],
  [['mascota', 'pet', 'animal'], 'paw'],
  [['tecnologia', 'electronico', 'gadget'], 'antenna'],
];

/**
 * Emoji guardado antes del catálogo → icono equivalente. Cubre los emoji que
 * podían salir de `suggestEmoji` y del picker viejo; lo que no esté aquí cae a
 * `FALLBACK_ICON` en la migración.
 */
export const EMOJI_TO_ICON: Record<string, string> = {
  '🍽️': 'tools-kitchen', '🍔': 'burger', '🍕': 'pizza', '🍣': 'fish', '🍤': 'fish',
  '🦞': 'fish', '🦐': 'fish', '🦑': 'fish', '🍗': 'grill', '🍖': 'meat', '🥩': 'meat',
  '🌮': 'meat', '🌯': 'meat', '🍝': 'soup', '🍜': 'soup', '🍲': 'soup', '🥘': 'soup',
  '🫕': 'soup', '🍛': 'soup', '🍱': 'bowl', '🥗': 'salad', '🥪': 'bread', '🥙': 'bread',
  '🌭': 'bread', '🥐': 'bread', '🥖': 'bread', '🧀': 'cheese', '🍦': 'ice-cream',
  '🍨': 'ice-cream', '🍰': 'cake', '🎂': 'cake', '🧁': 'cake', '🍮': 'cake',
  '🍪': 'cookie', '🍩': 'cookie', '🍫': 'candy', '🍬': 'candy', '🍭': 'candy',
  '🍓': 'apple', '🍎': 'apple', '🍌': 'apple', '🥭': 'apple', '🍋': 'lemon',
  '🥕': 'carrot', '🥚': 'egg', '🍳': 'egg', '🥛': 'milk', '☕': 'coffee', '🍵': 'coffee',
  '🧋': 'cup', '🥤': 'bottle', '🧃': 'bottle', '🍺': 'beer', '🍻': 'beer', '🍷': 'wine',
  '🥂': 'wine', '🍾': 'wine', '🍸': 'cup', '🍹': 'cup', '🧉': 'cup', '🛒': 'shopping-cart',
  '🧺': 'basket', '👨‍🍳': 'chef-hat', '🍿': 'candy',
  '🚗': 'car', '🚕': 'car', '🚙': 'car-suv', '🚌': 'bus', '🚐': 'bus', '🚇': 'train',
  '🚂': 'train', '🚆': 'train', '✈️': 'plane', '🛫': 'plane', '🛬': 'plane', '🚴': 'bike',
  '🚲': 'bike', '🏍️': 'motorbike', '🛵': 'scooter', '⛽': 'gas-station', '🅿️': 'parking',
  '🛣️': 'road', '🛤️': 'road', '🛳️': 'ship', '⛵': 'ship', '🚤': 'ship', '🚁': 'helicopter',
  '🚶': 'walk', '🚚': 'truck', '🚛': 'truck', '🚦': 'traffic-lights', '🗺️': 'map',
  '💊': 'pill', '💉': 'vaccine', '🏥': 'stethoscope', '🩺': 'stethoscope', '🦷': 'dental',
  '👓': 'eyeglass', '🩹': 'bandage', '🧘': 'yoga', '🏋️': 'barbell', '💪': 'barbell',
  '🏃': 'run', '🏊': 'swimming', '🧠': 'mood-smile', '🌡️': 'medical-cross', '🫀': 'heartbeat',
  '🚑': 'first-aid', '♿': 'wheelchair', '💆': 'massage',
  '📺': 'tv', '🎬': 'movie', '🎵': 'music', '🎶': 'music', '🎧': 'headphones',
  '🎮': 'gamepad', '🕹️': 'gamepad', '🎤': 'microphone', '🎙️': 'microphone', '📖': 'book',
  '📚': 'book', '🎨': 'palette', '🎉': 'confetti', '🪩': 'confetti', '🎊': 'confetti',
  '⚽': 'football', '🏀': 'basketball', '🎾': 'tennis', '🎱': 'pool', '🎳': 'puzzle',
  '🧩': 'puzzle', '♟️': 'chess', '🃏': 'cards', '🎴': 'cards', '🎸': 'guitar',
  '🎻': 'guitar', '🥁': 'guitar', '🎺': 'guitar', '🎹': 'guitar', '🏕️': 'campfire',
  '🎫': 'ticket', '🎟️': 'ticket',
  '👕': 'shirt', '👔': 'shirt', '👗': 'shirt', '👖': 'shirt', '👟': 'shoe', '👞': 'shoe',
  '👜': 'backpack', '🎒': 'backpack', '💍': 'diamond', '💎': 'diamond', '📦': 'shopping-bag',
  '🛍️': 'shopping-bag', '🏷️': 'tag', '💄': 'sparkles', '✨': 'sparkles', '🧴': 'sparkles',
  '💅': 'haircut', '💈': 'haircut', '🌸': 'perfume', '🎁': 'gift', '🧸': 'kid',
  '🏠': 'home', '🏡': 'home', '🏘️': 'building', '🏢': 'skyscraper', '💡': 'bulb',
  '🚿': 'droplet', '💧': 'droplet', '🔥': 'flame', '📡': 'wifi', '🛋️': 'sofa',
  '🛏️': 'bed', '🪴': 'plant', '🌱': 'plant', '🌿': 'plant', '🧹': 'trash', '🗑️': 'trash',
  '🔧': 'tools', '🔨': 'hammer', '🪚': 'tools', '🫙': 'wash-machine', '❄️': 'air-conditioning',
  '🔑': 'key', '♻️': 'recycle',
  '💰': 'cash', '💵': 'banknote', '💴': 'banknote', '💶': 'banknote', '💷': 'banknote',
  '💳': 'credit-card', '👛': 'wallet', '🐷': 'pig-money', '🐖': 'pig-money',
  '📈': 'chart-line', '📉': 'chart-line', '📊': 'report-money', '🪙': 'coin',
  '🧾': 'receipt', '📋': 'receipt-tax', '🏦': 'bank', '💸': 'exchange', '🛡️': 'shield',
  '⚖️': 'certificate', '🎯': 'businessplan',
  '💼': 'briefcase', '💻': 'laptop', '🖥️': 'desktop', '🎓': 'school', '🏫': 'school',
  '✏️': 'pencil', '📝': 'pencil', '🗓️': 'clock', '🔄': 'clock', '🌐': 'world',
  '👨‍👩‍👧': 'user-heart', '👶': 'baby', '🍼': 'baby',
  '🐾': 'paw', '🐶': 'dog', '🐕': 'dog', '🐱': 'cat', '🐈': 'cat',
  '🧳': 'luggage', '🏨': 'bed', '🏖️': 'beach', '⛰️': 'mountain', '🏔️': 'mountain',
  '📷': 'camera', '📸': 'camera', '🧭': 'compass', '⛺': 'tent', '🛂': 'world',
  '📱': 'mobile', '📲': 'mobile', '⌚': 'smartwatch', '🖨️': 'printer', '🤖': 'robot',
  '☁️': 'cloud', '🔋': 'battery', '🔌': 'antenna', '📀': 'server',
  '❤️': 'heart', '⭐': 'star', '📌': 'pin', '⛪': 'church', '🤲': 'hand-love',
  '🚨': 'medical-cross', '🙏': 'church',
};
