import {
  IconAlertCircle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBan,
  IconBell,
  IconBellOff,
  IconBolt,
  IconBrandGoogle,
  IconBrandWhatsapp,
  IconCalendar,
  IconCash,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleArrowDown,
  IconCircleArrowUp,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleX,
  IconClock,
  IconCopy,
  IconCreditCard,
  IconDeviceMobile,
  IconDiamond,
  IconDots,
  IconDownload,
  IconEdit,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFingerprint,
  IconFlag,
  IconGift,
  IconHammer,
  IconHome,
  IconHomeFilled,
  IconInfoCircle,
  IconInfoCircleFilled,
  IconLanguage,
  IconLock,
  IconLogout,
  IconMail,
  IconMinus,
  IconMoon,
  IconPalette,
  IconPencil,
  IconPhoto,
  IconPlayerPause,
  IconPlus,
  IconReceipt,
  IconRefresh,
  IconRepeat,
  IconSearch,
  IconSend,
  IconShare,
  IconShieldCheck,
  IconSparkles,
  IconStar,
  IconStarFilled,
  IconSun,
  IconTag,
  IconTool,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserFilled,
  IconUserMinus,
  IconUserPlus,
  IconUsers,
  IconUsersGroup,
  IconWallet,
  IconX,
} from '@tabler/icons-react-native';
import type { StyleProp, ViewStyle } from 'react-native';

const ICON_MAP = {
  'add': IconPlus,
  'alert-circle': IconAlertCircle,
  'arrow-back': IconArrowLeft,
  'arrow-down': IconArrowDown,
  'arrow-down-circle': IconCircleArrowDown,
  'arrow-forward': IconArrowRight,
  'arrow-up': IconArrowUp,
  'arrow-up-circle': IconCircleArrowUp,
  'arrow-up-circle-outline': IconCircleArrowUp,
  'ban-outline': IconBan,
  'calendar-outline': IconCalendar,
  'card-outline': IconCreditCard,
  'cash-outline': IconCash,
  'checkmark': IconCheck,
  'checkmark-circle': IconCircleCheckFilled,
  'checkmark-circle-outline': IconCircleCheck,
  'checkmark-done-circle-outline': IconChecks,
  'checkmark-done-outline': IconChecks,
  'checkmark-outline': IconCheck,
  'chevron-back': IconChevronLeft,
  'chevron-down': IconChevronDown,
  'chevron-forward': IconChevronRight,
  'chevron-forward-outline': IconChevronRight,
  'chevron-up': IconChevronUp,
  'close': IconX,
  'close-circle': IconCircleX,
  'close-circle-outline': IconCircleX,
  'close-outline': IconX,
  'color-palette': IconPalette,
  'construct-outline': IconTool,
  'copy-outline': IconCopy,
  'create-outline': IconEdit,
  'diamond-outline': IconDiamond,
  'document-outline': IconFile,
  'document-text-outline': IconFileText,
  'download-outline': IconDownload,
  'ellipsis-horizontal': IconDots,
  'eye-off-outline': IconEyeOff,
  'eye-outline': IconEye,
  'finger-print': IconFingerprint,
  'flag-outline': IconFlag,
  'flash-outline': IconBolt,
  'gift-outline': IconGift,
  'hammer': IconHammer,
  'hammer-outline': IconHammer,
  'home': IconHomeFilled,
  'home-outline': IconHome,
  'image-outline': IconPhoto,
  'information-circle': IconInfoCircleFilled,
  'information-circle-outline': IconInfoCircle,
  'language': IconLanguage,
  'language-outline': IconLanguage,
  'lock-closed': IconLock,
  'lock-closed-outline': IconLock,
  'log-out-outline': IconLogout,
  'logo-google': IconBrandGoogle,
  'logo-whatsapp': IconBrandWhatsapp,
  'mail-outline': IconMail,
  'moon-outline': IconMoon,
  'notifications-off-outline': IconBellOff,
  'notifications-outline': IconBell,
  'pause-circle': IconPlayerPause,
  'pause-circle-outline': IconPlayerPause,
  'pencil-outline': IconPencil,
  'people-circle-outline': IconUsersGroup,
  'people-outline': IconUsers,
  'person': IconUserFilled,
  'person-add-outline': IconUserPlus,
  'person-circle-outline': IconUserCircle,
  'person-outline': IconUser,
  'person-remove-outline': IconUserMinus,
  'phone-portrait-outline': IconDeviceMobile,
  'pricetag-outline': IconTag,
  'receipt-outline': IconReceipt,
  'refresh-circle-outline': IconRefresh,
  'refresh-outline': IconRefresh,
  'remove': IconMinus,
  'repeat': IconRepeat,
  'search': IconSearch,
  'search-outline': IconSearch,
  'send-outline': IconSend,
  'share-outline': IconShare,
  'shield-checkmark-outline': IconShieldCheck,
  'sparkles-outline': IconSparkles,
  'star': IconStarFilled,
  'star-outline': IconStar,
  'sunny-outline': IconSun,
  'time': IconClock,
  'time-outline': IconClock,
  'trash-outline': IconTrash,
  'wallet-outline': IconWallet,
} as const;

export type AppIconName = keyof typeof ICON_MAP;

interface AppIconProps {
  name: AppIconName;
  size?: number;
  color?: string;
  style?: StyleProp<ViewStyle>;
  strokeWidth?: number;
}

export default function AppIcon({ name, size = 24, color = '#000', style, strokeWidth = 2 }: AppIconProps) {
  const Icon = ICON_MAP[name];
  if (!Icon) return null;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
